# Generated by Django 5.2 on 2025-05-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
